// Generates netlify/functions/api/generated.js: the sql.js WASM binary (base64) and the sample CSVs,
// embedded as strings so the serverless bundle has no file-path dependencies.
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const wasm = readFileSync(join(dirname(require.resolve('sql.js')), 'sql-wasm.wasm'));
const sampleDir = join(here, '..', 'data', 'sample');
const sample = Object.fromEntries(readdirSync(sampleDir).filter(f => f.endsWith('.csv')).map(f => [f, readFileSync(join(sampleDir, f), 'utf8')]));
const out = join(here, '..', 'netlify', 'functions', 'api', 'generated.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// GENERATED by scripts/prepare-netlify.mjs. Do not edit.\nexport const WASM_B64 = ${JSON.stringify(wasm.toString('base64'))};\nexport const SAMPLE = ${JSON.stringify(sample)};\n`);
console.log(`wrote ${out} (${Math.round(wasm.length / 1024)} KB wasm, ${Object.keys(sample).length} sample files)`);
